[build]
target = "x86_64-os.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
#panic-abort-test = true

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
